### ISSUE TITLE
TypeError: No loop matching

### ISSUE THREAD

**Issue by yajuve94** [soheilrayatdoost/ContinuousEmotionDetection#1]
I cloned the repo and while running the code the following error came
```
Epoch 00023: val_loss did not improve from 0.00738
Epoch 24/25
143/143 [==============================] - 4s 25ms/step - loss: 0.0098 - val_loss: 0.0072

Epoch 00024: val_loss improved from 0.00738 to 0.00722, saving model to weights.bestFLF.hdf5
Epoch 25/25
143/143 [==============================] - 4s 25ms/step - loss: 0.0095 - val_loss: 0.0074

Epoch 00025: val_loss did not improve from 0.00722
Traceback (most recent call last):
  File "ContinousEmotionDetection.py", line 276, in <module>
    mseEeg,rmseEeg,pearsonCofEeg,prdictTestEeg  = evaluteSeq(modelEeg,testEeg,  labelTest,batchSize,lenSeqTest)
  File "ContinousEmotionDetection.py", line 181, in evaluteSeq
    mse, rmse, pearsonCof = metricSeq(labelreal, labelPredic, lenSeq)
  File "ContinousEmotionDetection.py", line 199, in metricSeq
    pearson.append(pearsonr(predictSeq, realSeq)[0])
  File "/usr/local/lib/python3.5/dist-packages/scipy/stats/stats.py", line 3410, in pearsonr
    xmean = x.mean(dtype=dtype)
  File "/home/lab06/.local/lib/python3.5/site-packages/numpy/core/_methods.py", line 75, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: No loop matching the specified signature and casting
was found for ufunc add
```
I changed my numpy version as mentioned [here](https://github.com/CSTR-Edinburgh/merlin/issues/466). But the error still persists. What to do now?

**Comment by soheilrayatdoost** [comment]
Try the solution that was mentioned in https://github.com/CSTR-Edinburgh/merlin/issues/470
